### ISSUE TITLE
New name of the project required

### ISSUE THREAD

**Issue by AsFaBw** [AsFaBw/greatfet-erica#1]
After having doubts whether the name "GreatFET" shall be used like indicated in the template, a question was sent to GSG. Michael Ossmann kindly addressed the question and created a guideline:

https://github.com/greatscottgadgets/greatfet/wiki/Board-Naming

Based on that the project shall not use "GreateFET" in its name. Further the first letter is dependent on names of already existing neighbors. So "Erica" would also violate that rule. Currently a plant beginning with "U" could be a candidate.

**Comment by AsFaBw** [comment]
"**Ulex-europaeus**", or "**Ulex**" in short, could be a candidate

**Comment by mossmann** [comment]
It isn't important for the name to start with a unique letter.  We're already through "V", so we've almost run out of letters!  I think it would be fine to continue calling it Erica.

**Comment by AsFaBw** [comment]
Thanks a lot for the feedback. That makes my life easier:-)
So my remaining task is to rename this repository (removing Greatfet within the name) and to register Erica to the neighbor site. Up to now, I am still trying understand the famous hacker paragraph of Germany. As all security analysis tools, also Erica could be used in the wrong manner... ...therefore I hesitated to upload any schematics/gerbers, as well as to register the name in the neighbors site. As soon as I am a bit more confident on the laws side, I will register the design.

**Comment by mossmann** [comment]
If you haven't renamed a project on github before, it is quite easy.  There will automatically be a redirect from the old project name to the new one.

**Comment by AsFaBw** [comment]
I did not know yet. I have just renamed the repository and with that I should be clean. 
Thanks a lot for the help and the clear guidelines you had prepared.
