### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by jhonathan282** [AsFaBw/greatfet-erica#10]
Where can i purchase a Erica Bord?

**Comment by AsFaBw** [comment]
It is a project not intended to be sold. Up to now I have not shared the schematics/gerbers on github as I have still in mind to improve for interrupts. Unfortuantely I am just doing that stuff in spare time and therefore progress is slow. If you provide me a possibility to contact you, we may find a solution. A gave already some boards to other interested...

**Comment by jhonathan282** [comment]
Thank you for your answar, here is my e-mail jhonathan282@protonmail.com .

**Comment by AsFaBw** [comment]
Board was sent...
