### ISSUE TITLE
library share to get started

### ISSUE THREAD

**Issue by pickeditmate** [AsFaBw/greatfet-erica#14]
Hi AsFaBw, are there any libraries you would recommend to get started with Erica? I've got some PCBs coming and want to get a head start getting my brain around writing code for the GreatFet.

Much obliged
PIM

**Comment by AsFaBw** [comment]
Hi, there is nothing what I can share, except some sample code.

**Comment by pickeditmate** [comment]
Emailed, thank you
PIM
