### ISSUE TITLE
J7_P10 incorrectly grounded

### ISSUE THREAD

**Issue by mossmann** [AsFaBw/greatfet-erica#5]
It looks like Erica has inherited this bug from neighbor-template.  Sorry!  This pin was once grounded on Azalea but was later changed to RTCX1. Fortunately it doesn't affect anything except the 32 kHz oscillator. If you want that to work you can snip the male pin off of J7_P10.

**Comment by AsFaBw** [comment]
Thanks a lot for the information - no problem at all. In order not to forget, I have immedeately corrected the issue in my schematics.
(Just for my internal tracking - V0.1/V0.2/V0.3 are affected)
