### ISSUE TITLE
You can learn from the design of yardstickone

### ISSUE THREAD

**Issue by leon-uhs** [AsFaBw/greatfet-erica#8]
You can learn from the design of yardstickone, it only needs a piece of CC1111 to complete 315.433.868.915 MHz

**Comment by AsFaBw** [comment]
Hi zhaohuansi, thanks a lot for the hint. In fact I did not know, that there is a balun covering from 300MHz-1GHz. So could be an option. I had seen baluns that either covered the 315-433 range or 868-915, but not over the full range. I am not an expert on the analog part, but I guess that the filters tuned for certain frequecies should be optimal for that target frequency. Even tuned for the target frequencies, you can even receive and transmit with the 433 Erica circuit within the 868 band as example. Reason to have more than one RF possibility is to send, receive and monitor in parallel.
By the way, as far as I know the RF circuit in the CC1111 is very similar than the CC1101. The CC1111 has in addition the cpu, that the GreatFET baseboard replaces. On the YardstickOne the CC1111 furhter controls the RF muxes/amps with ist GPIOs.
Thanks a lot for the hint.

**Comment by AsFaBw** [comment]
As I did not get any other reply, I will close this isssue. What solution is better I can't say and don't know. Most likely the Yardstick One is the option, when looking for better quality.
Anyhow, thanks again for the hint.
